language: node_js
node_js:
  - lts/*

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE apidb;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres

after_success: npm run coverage