site_name: Restful Calendar API

theme: mkdocs

repo_url: https://github.com/Ugo-M/Calendar-API/
edit_uri: ''

nav:
  - Home: index.md
  - Routes:
      - 'Index': 'routes/index.md'
      - 'Authentication': 'routes/authentication.md'
      - 'Calendar': 'routes/calendar.md'
      - 'Event': 'routes/event.md'
      - 'User': 'routes/user.md'
  - About: about.md
